# Generated by Django 2.1.7 on 2020-05-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_auto_20200508_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='badge_color',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
