# Generated by Django 2.1.15 on 2020-05-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_status_badge_color'),
        ('taskmanager', '0011_auto_20200511_0822'),
    ]

    operations = [
    ]
