# Generated by Django 2.1.7 on 2020-05-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0013_lastlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastlogin',
            old_name='current_last_login',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='lastlogin',
            old_name='previous_last_login',
            new_name='previous',
        ),
    ]
