# Generated by Django 2.1.15 on 2020-05-13 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0015_auto_20200513_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlogin',
            name='current',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 22, 21, 17, 745951), null=True),
        ),
        migrations.AlterField(
            model_name='lastlogin',
            name='previous',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 22, 21, 17, 745951), null=True),
        ),
    ]
