# Generated by Django 2.1.15 on 2020-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0018_auto_20200513_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastlogin',
            name='current',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lastlogin',
            name='previous',
            field=models.DateTimeField(null=True),
        ),
    ]
